### PR TITLE
Expose values hash instead of creating attr_list

### PR DESCRIPTION
**Pull request by rkam**
This is what I'm preferring to pull #6 

It still moves the common attributes to IOObject, and then just exposes the values hash.

Cleaner and less redundancy.

Still have redundant access to the properties, but that seems fine.

### CODE REVIEW

**Comment by abachman** [comment]
Hi @rkam, thanks for the updated pull request!

Change-wise it looks great, but I seem to be having some trouble running the new tests. It looks like dotenv needs to be added to the Gemfile, which is easy enough. But then I'm getting an error running the suite: 

```sh
$ bundle exec rake test
/Users/adam/.rvm/rubies/ruby-2.3.1/bin/ruby -S rspec ./spec/adafruit/io/client_spec.rb ./spec/adafruit/io/feed_spec.rb ./spec/io_spec.rb
/Users/adam/.rvm/gems/ruby-2.3.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:482:in `extract_scope_from': You must explicitly give a scope (:each, :all, or :suite) when using symbols as metadata for a hook. (ArgumentError)
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:475:in `scope_and_options_from'
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:453:in `register_hook'
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:290:in `before'
	from /Users/adam/projects/adafruit/io-client-ruby/spec/adafruit/io/feed_spec.rb:62:in `block (3 levels) in <top (required)>'
        ...
``` 

After changing `:example` to `:each` at https://github.com/adafruit/io-client-ruby/pull/8/files#diff-7a8f1afd24edbb7218fd83b6d14e0c85R62 (which may not be what you intended) I'm still getting 7 failing tests, are you seeing all passing on your machine?

I've set up the project on Adafruit's Travis CI account which should trigger [a build / test of this pull request](https://travis-ci.org/adafruit/io-client-ruby/pull_requests) if you update it.

Thanks for your patience as we sort this out, by the way. I'm new to Adafruit and still getting setup to support IO development. We appreciate your contribution to the project and I want to make sure we can merge it cleanly and update the gem so everyone gets the benefit.

**Comment by rkam** [comment]
Hmm, no, I get no errors.  Odd. I'll look into it more..   Sorry about that.

**Comment by abachman** [comment]
> I'm very sorry about that and for the hassle it caused - I had no idea.

Oh, no worries. Good catch on the rspec version. And thanks for your patience while we sort stuff out. 

Do you have local changes to your Gemfile or .gemspec? Feel free to add those to this request too. I don't have any objections to updating the rspec version required for development and if dotenv is required for testing, it should be included.

> Whatever you'd like to do is fine by me - if you want me to alter the tests so they work with 2.13.*, just close this out and I'll start on it. (Or whatever you'd like to do.)

Updating my local Gemfile like so

```diff
diff --git a/Gemfile b/Gemfile
index 7b63c56..970b74a 100644
--- a/Gemfile
+++ b/Gemfile
@@ -6,11 +6,12 @@ group :test do
   gem 'mime-types', '< 2.0.0'
   gem 'netrc', '~> 0.7.7'
   gem 'rb-fsevent', '~> 0.9'
-  gem 'rspec', '~> 2.13.0'
+  gem 'rspec', '~> 3.4.0'
   gem 'simplecov', :require => false
   gem 'test-queue', '~> 0.1.3'
   gem 'vcr', '~> 2.4.0'
   gem 'webmock', '~> 1.9.0'
+  gem 'dotenv', '~> 2.1.1'
 end
 
 platforms :rbx do
```

gets the test suite running with no other changes, and if the test suite is running I'm happy :)

I'd say fix the dependencies and we're good. After that I'll merge into master, make sure everything is groovy with Travis, figure out how to add you to a contributors list, and release an updated gem.

**Comment by rkam** [comment]
Hi Adam,

Thanks for working with me through all this.

I updated the Gemfile, but the Travis test is failing because there's no API KEY.
(I also added a check to the tests for that to make it clear why the test fails.)

Manual test works fine.

Unless you have some kind of test account/key, I don't see how this can be auto-tested.

I could also disable this particular test. It seems a shame though, given that it tests so much more. Unfortunately, I don't know of another way to do it.

**Comment by abachman** [comment]
lol, Travis will never work without a valid API key, I'm a dummy :D

I'm fine ignoring that for the time being. Eventually it'll make sense to have the automated test suite hit a local server (built into the test suite, similar to [io-client-go](https://github.com/adafruit/io-client-go)) and build an optional integration test suite that hits io.adafruit.com.

This looks great, I'm all green. 👍

**Pull request merged**
