### PR TITLE
You might be interested in this

### PR DESCRIPTION
**Pull request by rkam**
I made a couple of changes that I find useful.  Have a look and accept or not. :)

I moved the common instance attributes for Feed, Group, Data, etc. down to IOObject. It just makes the code a bit cleaner.

I also added a new attribute which contains the keys for the properties of the object itself so I could iterate through all the attributes without having to know them ahead of time. - Just a simple append to set when creating the accessor methods.

The only thing to double check is making actual accessors for :unsaved_values and :id_or_key to non-Feed classes.  Seemed like an oversight to me, but there could have been a reason for it..

### CODE REVIEW

**Comment by jwcooper** [comment]
This looks great, thank you! We'll test it out, and merge it as soon as we can.

**Comment by rkam** [comment]
Revisiting this...

It might be better to just make the @values hash accessible.  Then one could do feed.values.keys to get the info.  However, it also allows accessing the attributes via that hash, which you may not prefer to do.

Personally, I'm leaning toward abandoning this change and exposing values (clean and not redundant).  What do you think?

**Comment by jwcooper** [comment]
I think I like your latest suggestion. Easier this library is to use, the better.

**Comment by rkam** [comment]
Made the changes and issued another PR.   Since you prefer that too, I'll close this.

Thanks!

**Pull request closed without merging**
