### PR TITLE
Manual tests (only)

### PR DESCRIPTION
**Pull request by rkam**
I created a new suite of manual tests - ones that require an API key, which currently cover almost 90+% of the library code.

- Those that are missed are a couple of methods which fail (one each in `::Data` and `::Client`) and I believe need library changes.
- The bulk are in `::Group`, but I can't find the documentation on them at https://io.adafruit.com/api/docs/#!/Groups (and the deprecated one).
- Ignoring those, there's 100% coverage.

Here's the stats for the missing coverage:

     92.61% Code coverage
     95.12 %  data.rb     - #send_data missed - library issues
     97.78 %  client.rb   - #data      missed - library issues
     67.44 %  group.rb    - only undocumented methods missed
                              #create_group,  #send_group
                              #receive_group, #receive_next_group,
                              #groups(*args) (deprecated)
    
- There's a way to have `SimpleCov` ignore code (by wrapping it with `# :nocov:`).

I'd like to do that, if you don't mind - at least around  the deprecated `Group#groups` method.
I'm not sure about the other group methods - are they from an older version of the API or a future one or just not documented.  (btw, if the latter, then `#receive_previous_group` seems to be missing)

### CODE REVIEW

**Comment by abachman** [comment]
I think I understand where you're going with this change set, but it's a little big for one pull request, and I think the direct http testing will fit better in it's own project repository.

It looks like the goal was to write a comprehensive suite testing the io-client-ruby gem against io.adafruit.com, and then make all the same calls by hand with Faraday. Which should, all other things being equal, show whether the library correctly implements the API, is that right? I don't think we're going to merge this PR, but I think the goal is appropriate.

As far as an integration test suite is concerned, I think it would also be best if we kept it within either the tools we're already using (rspec) or a similar tool. An extremely extensive, _not-at-all-necessary-for-this-project_, example is the https://github.com/piotrmurach/github gem which splits local-only, library focused test into `spec/` and live tests into `features/` and wraps all those calls with VCR. This splits the live/local suites logically and keeps the tools standard, so extending the test suite is more straightforward. In fact, looking at that library, I may go in and [copy their stub helpers](https://github.com/piotrmurach/github/blob/master/spec/spec_helper.rb#L46) from the `spec` suite. They're nicer than mine :P.

Right now, the V1 API is frozen, so protection against the existing API changing out from under the library is probably not necessary, and might be overkill. All our work internally is going towards the V2 API. 

So, long winded, but I think we have to pass on this PR. Please get in touch with me directly (adam@adafruit.com) if you have any questions.

**Comment by rkam** [comment]
No problem.

Yeah, I created the HTTP tests as verification that the underlying API was working.
- when I wrote the tests, several parts of the ruby library were failing and I didn't know if it was the ruby code or the API itself.
- I had also looked at the python library, for instance, and saw some comments about certain calls not working, so knew that it could be the API (or, at least, had been at some point).
- Since I had written it, I figured I might as well include them - and also to help explain that the core code was written to support multiple testing methods.

Sorry it's big and out of scope and thanks for looking it over! :)  Again, not a problem passing on it.

--
btw, I do have some bug fixes to the library pending (that these caught), but was waiting for this to be closed before submitting - the tests now cover the fixed cases and I wanted to keep the PRs from getting messy or co-dependent.
I'll submit those (without any of these tests) a bit later.

**Comment by abachman** [comment]
> when I wrote the tests, several parts of the ruby library were failing and I didn't know if it was the ruby code or the API itself.

I totally feel you on that. As part of my first project with Adafruit, building the Go client (three weeks ago), I found and fixed a bug in the V1 Groups API. Handy to be able to reach into code on both sides of the fence :P 

The thing about V1 is that it's not used internally, we built it to expose the data but aren't using it day to day on any of the web interfaces. V2, on the other hand, will be used extensively in the web client and any mobile clients we end up building. So *that* API will be a better fit for the kind of deeper, live integration testing you were working towards. I expect we'll be building something like it into the project, in fact.

Also, feel free to include specs for new work using the local only `mock_request` and known-good JSON response style I set up in [feed_spec](https://github.com/adafruit/io-client-ruby/blob/master/spec/adafruit/io/feed_spec.rb), or change it up if another way is simpler or makes more sense. Having the tests will cover the library implementation, and if we're using "known-good" JSON from the API docs and our library code is correct, any example sketches we write with the library that break against production will expose bugs in the service.

Also, if you send me your email address offline, we've got some goodies we'd like to send your way :)

**Comment by rkam** [comment]
Thanks for the info about goodies, I'll send my email!

As for that part you quoted, just to be clear, it wasn't a complaint or anything like that.  I meant is as just an explanation/rationale of what I was did and why.  I was happy to do it and learn all about the API.

**Comment by abachman** [comment]
>  it wasn't a complaint or anything like that

Oh, no worries, I didn't take it as such. We get to learn about the API when things break, too :)

**Pull request closed without merging**
